package Picat.behavior;

/*Generated by MPS */


public class CommentLine_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public CommentLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.CommentLine";
  }
}
