package Picat.behavior;

/*Generated by MPS */


public abstract class FunctionRuleOrFact_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public FunctionRuleOrFact_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionRuleOrFact";
  }
}
