package Picat.behavior;

/*Generated by MPS */


public class FunctionDirectiveTable_BehaviorDescriptor extends FunctionDirective_BehaviorDescriptor {
  public FunctionDirectiveTable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionDirectiveTable";
  }
}
