package Picat.behavior;

/*Generated by MPS */


public class FunctionDirectivePrive_BehaviorDescriptor extends FunctionDirective_BehaviorDescriptor {
  public FunctionDirectivePrive_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionDirectivePrive";
  }
}
