package Picat.behavior;

/*Generated by MPS */


public class ImportFunctionItem_BehaviorDescriptor extends ImportModuleItem_BehaviorDescriptor {
  public ImportFunctionItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.ImportFunctionItem";
  }
}
