package Picat.behavior;

/*Generated by MPS */


public class ImportModuleItem_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public ImportModuleItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.ImportModuleItem";
  }
}
