package Picat.behavior;

/*Generated by MPS */


public class ImportDecl_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public ImportDecl_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.ImportDecl";
  }
}
