package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class PicatConcept_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PicatConcept_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.PicatConcept";
  }
}
