package Picat.behavior;

/*Generated by MPS */


public class Term_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Term_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Term";
  }
}
