package Picat.behavior;

/*Generated by MPS */


public class VariableNamed_BehaviorDescriptor extends Term_BehaviorDescriptor {
  public VariableNamed_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.VariableNamed";
  }
}
