package Picat.behavior;

/*Generated by MPS */


public class VariableAnonymous_BehaviorDescriptor extends Variable_BehaviorDescriptor {
  public VariableAnonymous_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.VariableAnonymous";
  }
}
