package Picat.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class LineExpression_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_pemto0_a(editorContext, node);
  }

  private EditorCell createCollection_pemto0_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_pemto0_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_pemto0_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_pemto0_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_pemto0_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "exp");
    editorCell.setCellId("Constant_pemto0_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createComponent_pemto0_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "Picat.editor.Eor");
    return editorCell;
  }
}
