package Picat.behavior;

/*Generated by MPS */


public abstract class Argument_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Argument_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Argument";
  }
}
