package Picat.behavior;

/*Generated by MPS */


public class Atom_BehaviorDescriptor extends Term_BehaviorDescriptor {
  public Atom_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Atom";
  }
}
