package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 1:
        return new CommentLine_BehaviorDescriptor();
      case 8:
        return new Root_BehaviorDescriptor();
      case 0:
        return new CommentBlock_BehaviorDescriptor();
      case 7:
        return new ModuleDecl_BehaviorDescriptor();
      case 3:
        return new FunctionDefinition_BehaviorDescriptor();
      case 2:
        return new EmptyLine_BehaviorDescriptor();
      case 4:
        return new FunctionPrivate_BehaviorDescriptor();
      case 5:
        return new FunctionTable_BehaviorDescriptor();
      case 9:
        return new Term_BehaviorDescriptor();
      case 6:
        return new LineExpression_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"Picat.structure.CommentBlock", "Picat.structure.CommentLine", "Picat.structure.EmptyLine", "Picat.structure.FunctionDefinition", "Picat.structure.FunctionPrivate", "Picat.structure.FunctionTable", "Picat.structure.LineExpression", "Picat.structure.ModuleDecl", "Picat.structure.Root", "Picat.structure.Term"};
}
