package Picat.behavior;

/*Generated by MPS */


public abstract class Body_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Body_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Body";
  }
}
