package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CommentLine_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements PicatConcept_BehaviorDescriptor {
  public CommentLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.CommentLine";
  }
}
