package Picat.behavior;

/*Generated by MPS */


public class CommentBlock_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public CommentBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.CommentBlock";
  }
}
