package Picat.behavior;

/*Generated by MPS */


public abstract class Condition_BehaviorDescriptor extends Goal_BehaviorDescriptor {
  public Condition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Condition";
  }
}
