package Picat.behavior;

/*Generated by MPS */


public abstract class DisjunctiveGoal_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public DisjunctiveGoal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.DisjunctiveGoal";
  }
}
