package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DisjunctiveGoal_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Goal_BehaviorDescriptor {
  public DisjunctiveGoal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.DisjunctiveGoal";
  }
}
