package Picat.behavior;

/*Generated by MPS */


public class EmptyLine_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public EmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.EmptyLine";
  }
}
