package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EnclosedGoal_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements NotConstraint_Or_EnclosedGoal_BehaviorDescriptor {
  public EnclosedGoal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.EnclosedGoal";
  }
}
