package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EquivConstraint_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements NegativeGoalOrEquivConstrain_BehaviorDescriptor {
  public EquivConstraint_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.EquivConstraint";
  }
}
