package Picat.behavior;

/*Generated by MPS */


public class Expression_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Expression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Expression";
  }
}
