package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class FunctionDirective_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements PicatConcept_BehaviorDescriptor {
  public FunctionDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionDirective";
  }
}
