package Picat.behavior;

/*Generated by MPS */


public abstract class FunctionDirective_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public FunctionDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionDirective";
  }
}
