package Picat.behavior;

/*Generated by MPS */


public class FunctionTable_BehaviorDescriptor extends FunctionDirective_BehaviorDescriptor {
  public FunctionTable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionTable";
  }
}
