package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FunctionDefinition_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements PicatConcept_BehaviorDescriptor {
  public FunctionDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionDefinition";
  }
}
