package Picat.behavior;

/*Generated by MPS */


public class FunctionRule_BehaviorDescriptor extends FunctionRuleOrFact_BehaviorDescriptor {
  public FunctionRule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionRule";
  }
}
