package Picat.behavior;

/*Generated by MPS */


public class FunctionPrivate_BehaviorDescriptor extends FunctionDirective_BehaviorDescriptor {
  public FunctionPrivate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionPrivate";
  }
}
