package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FunctionTable_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements FunctionDirective_BehaviorDescriptor {
  public FunctionTable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionTable";
  }
}
