package Picat.behavior;

/*Generated by MPS */


public class FunctionDef_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public FunctionDef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionDef";
  }
}
