package Picat.behavior;

/*Generated by MPS */


public class FunctionFact_BehaviorDescriptor extends FunctionRuleOrFact_BehaviorDescriptor {
  public FunctionFact_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.FunctionFact";
  }
}
