package Picat.behavior;

/*Generated by MPS */


public abstract class Goal_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Goal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Goal";
  }
}
