package Picat.behavior;

/*Generated by MPS */


public class Head_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Head_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Head";
  }
}
