package Picat.behavior;

/*Generated by MPS */


public class ImportItem_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public ImportItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.ImportItem";
  }
}
