package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LineExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Expression_BehaviorDescriptor {
  public LineExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.LineExpression";
  }
}
