package Picat.behavior;

/*Generated by MPS */


public class ModuleDecl_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public ModuleDecl_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.ModuleDecl";
  }
}
