package Picat.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class NegativeGoal_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements NegativeGoalOrEquivConstrain_BehaviorDescriptor {
  public NegativeGoal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.NegativeGoal";
  }
}
