package Picat.behavior;

/*Generated by MPS */


public class NegativeGoal_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public NegativeGoal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.NegativeGoal";
  }
}
