package Picat.behavior;

/*Generated by MPS */


public class Operator_BehaviorDescriptor extends PicatConcept_BehaviorDescriptor {
  public Operator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Operator";
  }
}
