package Picat.behavior;

/*Generated by MPS */


public abstract class Variable_BehaviorDescriptor extends Term_BehaviorDescriptor {
  public Variable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Picat.structure.Variable";
  }
}
