package Picat.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Operator_Constraints extends BaseConstraintsDescriptor {
  public Operator_Constraints() {
    super("Picat.structure.Operator");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("val", new BasePropertyConstraintsDescriptor("val", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "val";
        {
          String[] operators;
          operators = new String[]{"=", "!=", ">", ">=", "<", "<=", "=<", "..", "!", ",", ";", ":", "::", ".", ". ", "=>", "?=>", "==", "!==", ":=", "|", "$", "@", "/\\", "\\/", "~", "^", "<<", ">>", "+", "-", "*", "**", "/", "/>", "/<", "#=", "#!=", "#>", "@>=", "#<", "#<=", "#=<", "#/\\", "#\\/", "#~", "#^", "#=>", "#<=>", "@>", "@>=", "@<", "@<=", "@=<"};
          return Sequence.fromIterable(Sequence.fromArray(operators)).contains((SPropertyOperations.getString(propertyValue)));
        }
      }
    });
    return properties;
  }
}
